matrix:
  include:
    - language: node_js
      node_js:
        - 14
      cache:
        directories:
          - node_modules
      script: 
        - yarn test
        - yarn lint

    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - platform-tools
          - tools
          - build-tools-29.0.2
          - android-29
      before_install:
        - yes | sdkmanager "platforms;android-27"
      script:
        - ./gradlew assembleDebug