matrix:
  include:
    - language: node_js
      node_js:
        - 14
      cache:
        directories:
          - node_modules
      script: 
        - yarn test
        - yarn lint

    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - platform-tools
          - tools
          - build-tools-29.0.2
          - android-29
      before_install:
        - chmod +x gradlew
        - openssl aes-256-cbc -K "encrypted_cec398169802_key" -iv "encrypted_cec398169802_iv" -in my-release-key.keystore.enc -out my-release-key.keystore -d
        - tar -xvf my-release-key.keystore --overwrite
      script:
        - ./gradlew assembleDebug